let globalMediaFiles={},globalMessages=[],detectedSenders=new Set(),userAlignmentMap={},userAliasMap={},customBgBlob=null,customMusicBlob=null,mediaRecorder,recordedChunks=[],isRecording=false,searchHits=[],currentHitIndex=-1;
const $=(id)=>document.getElementById(id);
const filesInput=$('filesInput'),loaderUI=$('loaderUI'),chatUI=$('chatUI'),messagesDiv=$('messagesDiv'),syncOverlay=$('syncOverlay'),overlayText=$('overlayText'),overlaySubtext=$('overlaySubtext'),pixelBarContainer=$('pixelBarContainer'),pixelBarFill=$('pixelBarFill'),pixelBarText=$('pixelBarText'),toggleSettingsBtn=$('toggleSettingsBtn'),addMoreBtn=$('addMoreBtn'),settingsModal=$('settingsModal'),closeModalBtn=$('closeModalBtn'),purgeBtn=$('purgeBtn'),fullscreenBtn=$('fullscreenBtn'),searchInput=$('searchInput'),searchBtn=$('searchBtn'),applyFiltersBtn=$('applyFiltersBtn'),searchNav=$('searchNav'),searchNavCount=$('searchNavCount'),searchPrevBtn=$('searchPrevBtn'),searchNextBtn=$('searchNextBtn'),searchCloseBtn=$('searchCloseBtn'),filterSelect=$('filterSelect'),dateStart=$('dateStart'),dateEnd=$('dateEnd'),identityMatrix=$('identityMatrix'),applyMappingBtn=$('applyMappingBtn'),jumpDateSelect=$('jumpDateSelect'),jumpBtn=$('jumpBtn'),countInput=$('countInput'),countBtn=$('countBtn'),countResult=$('countResult'),bgInput=$('bgInput'),clearBgBtn=$('clearBgBtn'),musicInput=$('musicInput'),clearMusicBtn=$('clearMusicBtn'),globalAudioPlayer=$('globalAudioPlayer'),toggleMusicBtn=$('toggleMusicBtn'),recordBtn=$('recordBtn');
const vfxDictionary=[{class:'fx-fire',regex:/\b(fuego|calor|arde|quema|odio|enojo|rabia|maldit[oa]|hdp|ctm|put[oa]|mierda|mrd|carajo|verga|ptm|joder|estupid[oa]|imbecil|idiota|matar|muere|infierno|peligro|bala|sangre|golpe|pelea|callate|perra|cabron|pendejo|🔥|🤬|😡|💢)\b/i},{class:'fx-toxic',regex:/\b(ironia|sarcasmo|xd|xdd|lmao|lol|wtf|nmms|wey|weon|cringe|basado|funado|bruh|literal|esquizofrenia|xddd|XD|wtf|alv|clown|payaso|paja|chiste|random|bizarro|🤡|💩|💀|👽)\b/i},{class:'fx-love',regex:/\b(amor|te amo|te quiero|hermos[oa]|bonit[oa]|lind[oa]|precios[oa]|bb|bebe|bbita|corazon|vida mia|cielo|mi reina|mi rey|espos[oa]|novi[oa]|casate|beso|abrazo|cariño|ternura|perfect[oa]|magia|😍|🥰|😘|❤️|💕|💖|✨)\b/i},{class:'fx-cold',regex:/\b(frio|hielo|nieve|congelad[oa]|triste|lloro|dolor|depresion|ansiedad|rip|f|soledad|vacio|lagrimas|roto|corazon roto|muerto|fallecio|depre|agotad[oa]|cansad[oa]|😭|😢|💔|🥶|🧊)\b/i},{class:'fx-sick',regex:/\b(asco|enferm[oa]|vomito|mareo|virus|infeccion|asqueroso|pudre|podrido|malestar|🤢|🤮|🤧|🤒|🦠)\b/i},{class:'fx-gold',regex:/\b(dinero|plata|oro|rico|millonario|exito|ganar|premio|lujo|caro|billete|dolar|euro|cash|💰|💎|🤑|👑|💸)\b/i},{class:'fx-party',regex:/\b(fiesta|celebracion|feliz|alegria|cumpleaños|felicidades|wiii|yey|genial|epico|🎉|🎊|🥳|🍻|💃|🕺)\b/i},{class:'fx-shock',regex:/\b(omg|dios|wow|increible|susto|miedo|terror|sorpresa|wtf|imposible|😱|🤯|😳|😨|🫢)\b/i}];
function showProgressScreen(t,s){syncOverlay.style.display='flex';overlayText.innerText=t;overlaySubtext.innerText=s;pixelBarContainer.style.display='block';updateProgress(0)}
function updateProgress(p){pixelBarFill.style.width=p+'%';pixelBarText.innerText=p+'%'}
function hideProgressScreen(){syncOverlay.style.display='none';pixelBarContainer.style.display='none'}
fullscreenBtn.addEventListener('click',()=>{!document.fullscreenElement?document.documentElement.requestFullscreen().catch(()=>{}) : document.exitFullscreen&&document.exitFullscreen()});
function applyBackground(b){document.body.style.backgroundImage=`url('${URL.createObjectURL(b)}')`}
bgInput.addEventListener('change',e=>{if(e.target.files[0]){customBgBlob=e.target.files[0];applyBackground(customBgBlob)}});
clearBgBtn.addEventListener('click',()=>{customBgBlob=null;document.body.style.backgroundImage='none';bgInput.value=''});
function applyMusic(b){globalAudioPlayer.src=URL.createObjectURL(b);toggleMusicBtn.style.display='flex'}
musicInput.addEventListener('change',e=>{if(e.target.files[0]){customMusicBlob=e.target.files[0];applyMusic(customMusicBlob)}});
clearMusicBtn.addEventListener('click',()=>{customMusicBlob=null;globalAudioPlayer.src='';toggleMusicBtn.style.display='none';musicInput.value=''});
let isMusicPlaying=false;toggleMusicBtn.addEventListener('click',()=>{if(isMusicPlaying){globalAudioPlayer.pause();toggleMusicBtn.style.background='#0f172a';toggleMusicBtn.style.color='#00ff88'}else{globalAudioPlayer.play().catch(()=>{});toggleMusicBtn.style.background='#00ff88';toggleMusicBtn.style.color='#000'}isMusicPlaying=!isMusicPlaying});
countBtn.addEventListener('click',()=>{const w=countInput.value.trim().toLowerCase();if(!w){countResult.style.display='none';return}let t=0,c={};const re=new RegExp(w.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'gi');globalMessages.forEach(m=>{const mt=m.content.match(re);if(mt){t+=mt.length;c[m.sender]=(c[m.sender]||0)+mt.length}});let h=`<div class="text-[var(--sys-blue)] mb-1">TOTAL VECES: ${t}</div>`;for(let s in c)h+=`<div>${userAliasMap[s]||s}: <span class="text-white">${c[s]}</span></div>`;countResult.innerHTML=h;countResult.style.display='block'});
purgeBtn.addEventListener('click',()=>{if(confirm("¿Borrar memoria?"))try{db.transaction('dataStore','readwrite').objectStore('dataStore').clear().onsuccess=()=>location.reload()}catch(e){location.reload()}});
toggleSettingsBtn.addEventListener('click',()=>settingsModal.style.display='flex');
closeModalBtn.addEventListener('click',()=>settingsModal.style.display='none');
addMoreBtn.addEventListener('click',()=>filesInput.click());
recordBtn.addEventListener('click',async()=>{if(isRecording){if(mediaRecorder&&mediaRecorder.state!=='inactive') mediaRecorder.stop();return;}try{const displayStream = await navigator.mediaDevices.getDisplayMedia({video:{cursor:"always"},audio:true});const options = {mimeType:'video/webm;codecs=vp9'};if(!MediaRecorder.isTypeSupported(options.mimeType)){options.mimeType = 'video/webm;codecs=vp8';if(!MediaRecorder.isTypeSupported(options.mimeType)) options.mimeType='video/webm';}mediaRecorder = new MediaRecorder(displayStream, options);mediaRecorder.ondataavailable = e => { if(e.data.size>0) recordedChunks.push(e.data); };mediaRecorder.onstop = () => {const blob=new Blob(recordedChunks,{type:'video/webm'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.style.display='none';a.href=url;a.download=`AETHER_REC_${Date.now()}.webm`;document.body.appendChild(a);a.click();setTimeout(()=>{document.body.removeChild(a);window.URL.revokeObjectURL(url)},100);recordedChunks=[];displayStream.getTracks().forEach(track=>track.stop());isRecording=false;recordBtn.classList.remove('recording');recordBtn.innerText='🎥 REC';};displayStream.getVideoTracks()[0].onended = () => { if(isRecording) mediaRecorder.stop(); };mediaRecorder.start();isRecording=true;recordBtn.classList.add('recording');recordBtn.innerText='⏹ STOP';}catch(err){console.error(err);alert('Error: '+err.message);}});
function buildIdentityMatrixUI(){identityMatrix.innerHTML='';const frag=document.createDocumentFragment();Array.from(detectedSenders).forEach((s,i)=>{let da=userAlignmentMap[s]||((s.toLowerCase()==='yo'||i===0)?'right':'left');userAlignmentMap[s]=da;let ca=userAliasMap[s]||'',ss=s.replace(/"/g,'&quot;'),r=document.createElement('div');r.className='identity-row';r.innerHTML=`<div class="text-[10px] font-sys text-gray-300 truncate" title="${s}">${s}</div><div><input type="text" class="sys-input py-1 px-2 rounded text-[10px] alias-input" data-user="${ss}" placeholder="Alias..." value="${ca}"></div><div class="radio-group"><label><input type="radio" name="align_${i}" value="left" class="radio-input align-trigger" data-user="${ss}" ${da==='left'?'checked':''}><span class="radio-label left-side">IZQ</span></label><label><input type="radio" name="align_${i}" value="right" class="radio-input align-trigger" data-user="${ss}" ${da==='right'?'checked':''}><span class="radio-label right-side">DER</span></label></div>`;frag.appendChild(r)});identityMatrix.appendChild(frag)}
applyMappingBtn.addEventListener('click',async()=>{document.querySelectorAll('.alias-input').forEach(i=>{const u=i.getAttribute('data-user'),v=i.value.trim();if(v)userAliasMap[u]=v;else delete userAliasMap[u]});document.querySelectorAll('.align-trigger:checked').forEach(r=>{userAlignmentMap[r.getAttribute('data-user')]=r.value});settingsModal.style.display='none';showProgressScreen("APLICANDO","Guardando...");updateProgress(50);await saveStateToDB();await renderChat()});
async function renderChat(){showProgressScreen("CONSTRUYENDO","Inyectando Efectos...");messagesDiv.innerHTML='';let ld="";const fg=document.createDocumentFragment();jumpDateSelect.innerHTML='<option value="">[ SELECCIONAR FECHA ]</option>';const tm=globalMessages.length;for(let i=0;i<tm;i++){const m=globalMessages[i],iso=m.dateObj.toISOString().split('T')[0],dd=m.dateObj.toLocaleDateString();if(dd!==ld&&dd!=="Invalid Date"){const dv=document.createElement('div');dv.className="date-divider filter-item";dv.setAttribute('data-isodata',iso);dv.innerHTML=`<span>${dd}</span>`;fg.appendChild(dv);ld=dd;const o=document.createElement('option');o.value=iso;o.text=dd;jumpDateSelect.appendChild(o)}const ir=(userAlignmentMap[m.sender]||'left')==='right',dn=userAliasMap[m.sender]||m.sender;let fc=processMediaContent(m.content).replace(/\n/g,'<br>'),mt='text';if(fc.includes('class="sticker-file"'))mt='sticker';else if(fc.includes('<img'))mt='photo';else if(fc.includes('<video'))mt='video';else if(fc.includes('<audio'))mt='audio';let fx='';for(let v of vfxDictionary)if(v.regex.test(m.content)){fx=v.class;break}const div=document.createElement('div');div.className=`msg-container filter-item ${ir?'msg-right':'msg-left'}`;div.setAttribute('data-content',m.content.toLowerCase());div.setAttribute('data-isodata',iso);div.setAttribute('data-type',mt);div.innerHTML=`<div class="msg-wrapper ${fx}"><div class="name-label">${dn}</div><div class="text-[0.85rem] leading-relaxed text-gray-200">${fc}</div><div class="timestamp">${dd} - ${m.dateObj.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</div></div>`;fg.appendChild(div);if(i%800===0||i===tm-1){updateProgress(Math.floor(((i+1)/tm)*100));await new Promise(r=>setTimeout(r,0))}}messagesDiv.appendChild(fg);applyFilters();setTimeout(()=>{window.scrollTo(0,document.body.scrollHeight);hideProgressScreen()},50)}
function processMediaContent(t){let r=t;for(let fn in globalMediaFiles){const re=new RegExp(fn.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'g');if(re.test(t)){const u=globalMediaFiles[fn].url,ex=fn.split('.').pop().toLowerCase(),is=ex==='webp'||fn.toUpperCase().includes('STK');if(is)r=r.replace(re,`<br><img src="${u}" class="sticker-file" loading="lazy">`);else if(['jpg','jpeg','png','gif'].includes(ex))r=r.replace(re,`<br><img src="${u}" class="media-file" loading="lazy">`);else if(['mp4','webm'].includes(ex))r=r.replace(re,`<br><video controls src="${u}" class="media-file"></video>`);else if(['opus','ogg','mp3','m4a','wav'].includes(ex))r=r.replace(re,`<br><audio controls src="${u}" class="media-file mt-1"></audio>`);else r=r.replace(re,`<br><a href="${u}" download="${fn}" class="text-[var(--sys-blue)] text-xs font-bold underline mt-1 block">DESCARGAR</a>`)}}return r}
function applyFilters(){const ft=filterSelect.value,sd=dateStart.value,ed=dateEnd.value;document.querySelectorAll('.filter-item').forEach(el=>{const iso=el.getAttribute('data-isodata');let v=true;if(sd&&iso<sd)v=false;if(ed&&iso>ed)v=false;if(el.classList.contains('date-divider'))el.style.display=v?'flex':'none';else{const ty=el.getAttribute('data-type'),mt=ft==='all'||ty===ft;el.style.display=(v&&mt)?'flex':'none'}})}
applyFiltersBtn.addEventListener('click',()=>{applyFilters();settingsModal.style.display='none'});
function performSearch(){const q=searchInput.value.toLowerCase().trim();document.querySelectorAll('.msg-wrapper').forEach(w=>{w.style.boxShadow='';w.style.border=''});if(!q){searchHits=[];currentHitIndex=-1;searchNav.classList.add('hidden');return}searchHits=Array.from(document.querySelectorAll('.filter-item:not(.date-divider)')).filter(m=>m.getAttribute('data-content').includes(q)&&m.style.display!=='none');if(searchHits.length>0){currentHitIndex=0;searchNav.classList.remove('hidden');updateSearchNav();focusSearchHit();settingsModal.style.display='none'}else{alert('No se encontraron coincidencias');searchNav.classList.add('hidden')}}
function updateSearchNav(){searchNavCount.innerText=`${currentHitIndex+1}/${searchHits.length}`}
function focusSearchHit(){const t=searchHits[currentHitIndex],w=t.querySelector('.msg-wrapper');document.querySelectorAll('.msg-wrapper').forEach(x=>{x.style.boxShadow='';x.style.border=''});w.style.transition="all 0.3s";w.style.boxShadow="0 0 20px rgba(255, 255, 0, 0.8)";w.style.border="2px solid yellow";t.scrollIntoView({behavior:'smooth',block:'center'})}
searchBtn.addEventListener('click',performSearch);
searchInput.addEventListener('keydown',(e)=>{if(e.key==='Enter')performSearch()});
searchNextBtn.addEventListener('click',()=>{if(searchHits.length>0){currentHitIndex=(currentHitIndex+1)%searchHits.length;updateSearchNav();focusSearchHit()}});
searchPrevBtn.addEventListener('click',()=>{if(searchHits.length>0){currentHitIndex=(currentHitIndex-1+searchHits.length)%searchHits.length;updateSearchNav();focusSearchHit()}});
searchCloseBtn.addEventListener('click',()=>{searchNav.classList.add('hidden');document.querySelectorAll('.msg-wrapper').forEach(w=>{w.style.boxShadow='';w.style.border=''});searchHits=[];currentHitIndex=-1});
jumpBtn.addEventListener('click',()=>{const td=jumpDateSelect.value;if(!td)return;const el=document.querySelector(`.date-divider[data-isodata="${td}"]`);if(el){settingsModal.style.display='none';window.scrollTo({top:el.getBoundingClientRect().top+window.pageYOffset-65,behavior:"smooth"});el.querySelector('span').style.borderColor="var(--sys-alert)";el.querySelector('span').style.color="var(--sys-alert)";setTimeout(()=>{el.querySelector('span').style.borderColor="#333";el.querySelector('span').style.color="#94a3b8"},2000)}});
